### PR TITLE
Report page

### PR DESCRIPTION
**Pull request by emilycritter**
Guys... I've been working really hard. Super exciting stuff. The data in the line graph isn't correct yet, but I figured we could do that as a group or in a pair tomorrow.

### CODE REVIEW

**Comment by emilycritter** [comment]
dailyshowguests

**Comment by darrenga** [comment]
Looks great Emily!

**Comment by darrenga** [comment]
Yes....sounds great....we can wrap it up tomorrow

**Comment by durdyburd** [comment]
Holy cow, this is fantastic work. Excellent job and many thanks!

**Pull request merged**
