### PR TITLE
Start report page

### PR DESCRIPTION
**Pull request by emilycritter**
This added the graph for the report page and did some formatting/styling on this page. The graph is still not updating dynamically - but the output of "@bar_chart_data" matches the text input exactly.

### CODE REVIEW

**Comment by emilycritter** [comment]
daily_show_guests_ _ruby_bin_rails_s_ _80x24

**Comment by emilycritter** [comment]
guests_controller_rb_ __users_emilyritter_documents_projects_tiy_lab4-dataset-group

**Comment by emilycritter** [comment]
Please go ahead and merge.

**Comment by durdyburd** [comment]
:-1:

**Pull request merged**
