### PR TITLE
Remove 'turbolinks' from application.js. Bar chart now dynamic

### PR DESCRIPTION
**Pull request by emilycritter**
Remove 'turbolinks' from application.js to get charts to load every refresh. Code for bar chart is now dynamic, but if time, Jwo recommends changing code in controller.

### CODE REVIEW

**Comment by emilycritter** [comment]
view-source_localhost_3000_guests_index

From this...

**Comment by emilycritter** [comment]
To this...
view-source_localhost_3000_guests_index

**Comment by emilycritter** [comment]
Please accept.

**Comment by durdyburd** [comment]
:-1:

**Pull request merged**
